---
- name: Setup Flask App
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-setuptools
          - python3-venv
          - nginx
        state: present

    - name: Install Flask
      pip:
        name: flask

    - name: Create application directory
      file:
        path: /home/vagrant/myproject
        state: directory
        owner: vagrant
        group: vagrant

    - name: Copy Flask application
      copy:
        src: /vagrant/myproject/myproject.py
        dest: /home/vagrant/myproject/myproject.py
        owner: vagrant
        group: vagrant
        remote_src: true

    - name: Create virtual environment
      command: python3 -m venv /home/vagrant/myproject/myprojectenv
      args:
        creates: /home/vagrant/myproject/myprojectenv/bin/activate

    - name: Install wheel in virtual environment
      pip:
        name: wheel
        virtualenv: /home/vagrant/myproject/myprojectenv

    - name: Install packages from requirements.txt
      pip:
        requirements: /vagrant/requirements.txt
        virtualenv: /home/vagrant/myproject/myprojectenv

    - name: Allow port 5000 through UFW
      ufw:
        rule: allow
        port: 5000
        proto: tcp

    - name: Copy systemd service file for Gunicorn
      copy:
        src: /vagrant/systemd/myproject.service
        dest: /etc/systemd/system/myproject.service
        remote_src: true

    - name: Reload systemd to pick up the new service file
      command: sudo systemctl daemon-reload

    - name: Start and enable Gunicorn service
      systemd:
        name: myproject
        state: started
        enabled: yes

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    
    - name: Copy systemd file for Nginx
      copy:
        src: /vagrant/systemd/myproject
        dest: /etc/nginx/sites-available/myproject
        remote_src: true

    - name: Enable the Nginx site configuration
      file:
        src: /etc/nginx/sites-available/myproject
        dest: /etc/nginx/sites-enabled/myproject
        state: link

    - name: Test Nginx configuration
      command: nginx -t

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Remove UFW rule for port 5000
      ufw:
        rule: allow
        port: 5000
        proto: tcp

    - name: Allow 'Nginx Full' through UFW
      ufw:
        rule: allow
        name: 'Nginx Full'